import test from 'node:test';import assert from 'node:assert/strict';
import {freshProgress,buy,reward,validateProgress} from '../src/progress.js';
import {createRun,stepRun,walkable,runDifficulty,memoryDifficulty} from '../src/engine.js';
test('Shared equipment costs exactly once and cannot overspend',()=>{const p=freshProgress();assert.equal(buy(p,'trail'),true);assert.equal(p.credits,38);assert.equal(buy(p,'trail'),false);p.credits=0;assert.equal(buy(p,'shield'),false);assert.deepEqual(p.items,['trail']);});
test('Game rewards persist in the same inventory and progression',()=>{const p=freshProgress();reward(p,'run');reward(p,'memory');assert.equal(p.credits,63);assert.equal(p.xp,50);assert.equal(p.level,2);assert.deepEqual(p.items,['badge']);assert.deepEqual(validateProgress(p),p);});
test('Imported progress rejects invalid quantities and unknown equipment',()=>{const p=freshProgress();assert.throws(()=>validateProgress({...p,credits:-1}));assert.throws(()=>validateProgress({...p,items:['unknown']}));assert.throws(()=>validateProgress({...p,equipped:'shield'}));});
test('Equipment changes gameplay and walls block movement',()=>{assert.equal(createRun(1,'shield').hearts,4);assert.equal(createRun(1,'trail').speed,205);assert.equal(walkable(220,140),false);const r=createRun();r.phase='running';r.player={x:175,y:135};stepRun(r,.03,{x:1,y:0});assert.equal(r.player.x,175);});
test('Collect all relics and reach portal to win; timeout loses',()=>{const r=createRun();r.phase='running';for(const gem of r.gems){r.player={x:gem.x,y:gem.y};stepRun(r,0,{x:0,y:0});}assert.equal(r.collected,6);r.player={...r.portal};stepRun(r,0,{x:0,y:0});assert.equal(r.phase,'won');const timeout=createRun();timeout.phase='running';timeout.time=.01;stepRun(timeout,.02,{x:0,y:0});assert.equal(timeout.phase,'lost');});

test('Stages progressively reduce time and increase hazards without changing equipment bonuses',()=>{for(let stage=2;stage<=9;stage++){const before=runDifficulty(stage-1),after=runDifficulty(stage);assert.ok(after.time<before.time);assert.ok(after.enemyFrequency>before.enemyFrequency);assert.ok(after.enemyCount>=before.enemyCount);assert.ok(after.hitProtection<before.hitProtection);const m=memoryDifficulty(stage-1),previous=memoryDifficulty(stage-2);assert.ok(m.time<previous.time);assert.ok(m.study<previous.study);assert.ok(m.pairs>=previous.pairs);assert.ok(m.penalty>=previous.penalty);}const r=createRun(9,'shield');assert.equal(r.time,50);assert.equal(r.enemies.length,8);assert.equal(r.hearts,4);assert.equal(memoryDifficulty(8).pairs,12);assert.equal(memoryDifficulty(8,'lantern').study-memoryDifficulty(8).study,2000);});
