import {chromium as playwright} from 'playwright';
import chromium from '@sparticuz/chromium';
import {prepareBrowser} from './prepare-browser.mjs';
import {encodeFunctionResult,decodeFunctionData,parseAbi,encodeEventTopics} from 'viem';
import {mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
import {server} from '../scripts/serve.mjs';
const account='0x1111111111111111111111111111111111111111',wallet='0x2222222222222222222222222222222222222222';
const abi=parseAbi(['function balanceOf(address) view returns (uint256)','function ownerOf(uint256) view returns (address)','function generation(uint256) view returns (uint8)','function tokenBoundAccount(uint256) view returns (address)','function familyOf(uint256) view returns (uint8)','function seedOf(uint256) view returns (uint32)','function frames(uint8,uint32) view returns (uint256[64])','event Transfer(address indexed from,address indexed to,uint256 indexed tokenId)']);
const topics=encodeEventTopics({abi,eventName:'Transfer',args:{from:'0x0000000000000000000000000000000000000000',to:account,tokenId:1n}});
const errors=[];let generation=1;
const browser=await playwright.launch({executablePath:prepareBrowser(),args:chromium.args,headless:true});
await mkdir('artifacts',{recursive:true});
try{for(const width of [1360,390]){
 const context=await browser.newContext({viewport:{width,height:950}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>new URL(route.request().url()).hostname==='localhost'?route.continue():route.abort());
 await page.goto('http://localhost:4173');await page.evaluate(()=>localStorage.clear());await page.reload();await page.getByRole('heading',{name:'Your home',exact:true}).waitFor();assert.equal(await page.locator('#connection').textContent(),'DEMO · NO WALLET');
 await page.locator('nav [data-app="shop"]').click();await page.locator('[data-buy="trail"]').click();await page.getByRole('button',{name:'Confirm simulated purchase'}).click();await page.locator('nav [data-app="inventory"]').click();await page.getByRole('button',{name:'Equip',exact:true}).click();assert.equal(await page.locator('#credits').textContent(),'38');
 await page.locator('nav [data-app="run"]').click();await page.getByRole('button',{name:'Begin expedition'}).click();await page.locator('#game').focus();await page.keyboard.down('ArrowRight');await page.waitForTimeout(500);await page.keyboard.up('ArrowRight');await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByRole('heading',{name:'Take a breath.'}).waitFor();
 await page.locator('nav [data-app="memory"]').click();await page.getByRole('button',{name:'Start a round'}).click();await page.locator('[data-card]').first().waitFor();const cards=await page.locator('[data-card]').allTextContents();await page.waitForFunction(()=>!document.querySelector('[data-card]').disabled);for(const symbol of [...new Set(cards)]){for(const i of cards.map((v,i)=>v===symbol?i:-1).filter(i=>i>=0))await page.locator(`[data-card="${i}"]`).click();await page.waitForTimeout(400);}assert.equal(await page.locator('#credits').textContent(),'43');
 await page.locator('nav [data-app="wallet"]').click();assert.match(await page.locator('#panel').textContent(),/EXAMPLE FRIEND WALLET/);await page.reload();await page.getByRole('heading',{name:'Your home',exact:true}).waitFor();assert.equal(await page.locator('#credits').textContent(),'43');await page.locator('nav [data-app="run"]').click();await page.screenshot({path:`artifacts/demo-${width}.png`,fullPage:true});

 await page.evaluate(()=>{const p=JSON.parse(localStorage.getItem('friendos:demo:v1'));p.level=9;p.wins=8;p.memoryWins=8;p.items=['trail','shield','lantern','badge'];p.equipped='shield';localStorage.setItem('friendos:demo:v1',JSON.stringify(p));});await page.reload();await page.locator('nav [data-app="run"]').click();assert.match(await page.locator('#run-overlay').textContent(),/50 seconds/);assert.match(await page.locator('#run-overlay').textContent(),/8 wisps/);assert.match(await page.locator('#run-overlay').textContent(),/4 hearts/);await page.locator('nav [data-app="inventory"]').click();assert.equal(await page.locator('[data-equip="badge"]').count(),0);await page.locator('[data-equip="lantern"]').click();await page.locator('nav [data-app="memory"]').click();assert.match(await page.locator('.memory-header').textContent(),/Stage 9/);assert.match(await page.locator('.memory-header').textContent(),/3.2s/);await page.getByRole('button',{name:'Start a round'}).click();await page.locator('[data-card]').first().waitFor();assert.equal(await page.locator('[data-card]').count(),24);const stageCards=await page.locator('[data-card]').allTextContents();await page.waitForFunction(()=>!document.querySelector('[data-card]').disabled);const different=stageCards.findIndex(c=>c!==stageCards[0]);await page.locator('[data-card="0"]').click();await page.locator(`[data-card="${different}"]`).click();await page.waitForFunction(()=>document.querySelector('#memory-status').textContent.includes('Wrong pair'));await page.waitForTimeout(300);assert.ok(parseFloat(await page.locator('#memory-time').textContent())<=37);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Late stage mobile layout fits');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No horizontal overflow');console.log(`Browser flow passed at ${width}px`);
 }
 assert.deepEqual(errors,[]);console.log('No browser errors. Mocks are automated test fixtures only.');
}finally{await browser.close();server.close();}
