import {chromium as playwright} from 'playwright';
import chromium from '@sparticuz/chromium';
import {prepareBrowser} from './prepare-browser.mjs';
import {encodeFunctionResult,decodeFunctionData,parseAbi,encodeEventTopics} from 'viem';
import {mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
import {server} from '../scripts/serve.mjs';
const account='0x1111111111111111111111111111111111111111',wallet='0x2222222222222222222222222222222222222222';
const abi=parseAbi(['function balanceOf(address) view returns (uint256)','function ownerOf(uint256) view returns (address)','function generation(uint256) view returns (uint8)','function tokenBoundAccount(uint256) view returns (address)','function familyOf(uint256) view returns (uint8)','function seedOf(uint256) view returns (uint32)','function frames(uint8,uint32) view returns (uint256[64])','event Transfer(address indexed from,address indexed to,uint256 indexed tokenId)']);
const topics=encodeEventTopics({abi,eventName:'Transfer',args:{from:'0x0000000000000000000000000000000000000000',to:account,tokenId:1n}});
const errors=[];let generation=1;let rejectPublic=false;let publicQueries=0;
const browser=await playwright.launch({executablePath:prepareBrowser(),args:chromium.args,headless:true});
await mkdir('artifacts',{recursive:true});
try{for(const width of [1360,390]){
 const context=await browser.newContext({viewport:{width,height:950}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.exposeFunction('fixtureRpc',async req=>{switch(req.method){case'eth_requestAccounts':return[account];case'eth_accounts':return[account];case'eth_chainId':return'0x1237';case'eth_blockNumber':return'0x42c1d80';case'eth_getLogs':throw new Error('Wallet RPC does not support eth_getLogs');case'fixture_logs':return req.params[0].topics?.[2]?.toLowerCase().endsWith(account.slice(2))?[{address:'0x14c49e6118f46525de9ab41a51cbaa3c6ebf181d',topics,data:'0x',blockNumber:'0x3cbd8c0',transactionHash:'0x'+'ab'.repeat(32),transactionIndex:'0x0',blockHash:'0x'+'cd'.repeat(32),logIndex:'0x0',removed:false}]:[];case'eth_call':{const call=decodeFunctionData({abi,data:req.params[0].data});const result=call.functionName==='balanceOf'?1000000000000000000n:call.functionName==='ownerOf'?(call.args[0]===2n?'0x3333333333333333333333333333333333333333':account):call.functionName==='generation'?(call.args[0]===3n?0:generation):call.functionName==='tokenBoundAccount'?wallet:call.functionName==='familyOf'?0:call.functionName==='seedOf'?123:call.functionName==='frames'?Array.from({length:64},()=>0x18183c3c7e7e18181818181818181818n):null; // generation balance is one token; RF balance is one RF
 const actual=call.functionName==='balanceOf'&&req.params[0].to.toLowerCase()==='0x14c49e6118f46525de9ab41a51cbaa3c6ebf181d'?1n:result;
 return encodeFunctionResult({abi,functionName:call.functionName,result:actual});}default:throw new Error('Unexpected wallet method '+req.method);}});
 await page.addInitScript(()=>{const callbacks={};window.ethereum={request:r=>window.fixtureRpc(r),on:(name,fn)=>callbacks[name]=fn,removeListener:()=>{}};window.fixtureChangeAccount=()=>callbacks.accountsChanged?.([]);});
 await page.route('https://rpc.mainnet.chain.robinhood.com/**',async route=>{publicQueries++;const req=route.request().postDataJSON();if(rejectPublic){await route.fulfill({json:{jsonrpc:'2.0',id:req.id,error:{code:-32601,message:'History unavailable'}}});return;}const result=await page.evaluate(r=>window.fixtureRpc({...r,method:'fixture_logs'}),req);await route.fulfill({json:{jsonrpc:'2.0',id:req.id,result}});});
 await page.goto('http://localhost:4173');await page.evaluate(()=>localStorage.clear());rejectPublic=false;await page.reload();await page.getByRole('button',{name:'Use my real Friend',exact:true}).click();await page.getByRole('button',{name:'Connect wallet',exact:true}).click();await page.getByRole('button',{name:'Friend #1 Generation 1 · Select'}).click();await page.getByRole('heading',{name:'Your home',exact:true}).waitFor();
 await page.locator('nav [data-app="shop"]').click();await page.locator('[data-buy="trail"]').click();await page.getByRole('button',{name:'Confirm simulated purchase'}).click();await page.locator('nav [data-app="inventory"]').click();assert.equal(await page.locator('#credits').textContent(),'38');await page.getByRole('button',{name:'Equip',exact:true}).click();
 await page.locator('nav [data-app="run"]').click();await page.screenshot({path:`artifacts/relic-run-${width}.png`,fullPage:true});await page.getByRole('button',{name:'Begin expedition'}).click();await page.locator('#game').focus();await page.keyboard.down('ArrowRight');await page.waitForTimeout(500);await page.keyboard.up('ArrowRight');await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByRole('heading',{name:'Take a breath.'}).waitFor();await page.screenshot({path:`artifacts/paused-${width}.png`,fullPage:true});
 await page.locator('nav [data-app="memory"]').click();await page.getByRole('button',{name:'Start a round'}).click();await page.locator('[data-card]').first().waitFor();const cards=await page.locator('[data-card]').allTextContents();await page.waitForFunction(()=>!document.querySelector('[data-card]').disabled);for(const symbol of [...new Set(cards)]){const indices=cards.map((v,i)=>v===symbol?i:-1).filter(i=>i>=0);for(const i of indices)await page.locator(`[data-card="${i}"]`).click();await page.waitForFunction(()=>document.querySelectorAll('.memory-tile.matched').length>=document.querySelectorAll('.memory-tile').length||!Array.from(document.querySelectorAll('[data-card]')).some(c=>c.textContent!=='?'&&!c.classList.contains('matched')));}assert.equal(await page.locator('#credits').textContent(),'43');await page.screenshot({path:`artifacts/memory-${width}.png`,fullPage:true});
 rejectPublic=true;await page.reload();await page.getByRole('button',{name:'Use my real Friend',exact:true}).click();await page.getByRole('button',{name:'Connect wallet',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#gate-status').textContent.includes('Enter your Friend token ID'));for(const [id,message] of [['2','not owned'],['3','generation 0']]){await page.getByLabel('Friend token ID').fill(id);await page.getByRole('button',{name:'Verify this Friend',exact:true}).click();await page.waitForFunction(text=>document.querySelector('#gate-status').textContent.includes(text),message);assert.equal(await page.locator('#workspace').isVisible(),false);}await page.getByLabel('Friend token ID').fill('1');await page.getByRole('button',{name:'Verify this Friend',exact:true}).click();await page.getByRole('button',{name:'Friend #1 Generation 1 · Select'}).click();rejectPublic=false;await page.getByRole('heading',{name:'Your home',exact:true}).waitFor();assert.equal(await page.locator('#credits').textContent(),'43');await page.locator('nav [data-app="inventory"]').click();await page.getByRole('heading',{name:'Trail Shoes'}).waitFor();await page.getByRole('button',{name:'Unequip',exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No horizontal overflow');await page.evaluate(()=>window.fixtureChangeAccount());await page.locator('#gate').waitFor({state:'visible'});console.log(`Browser flow passed at ${width}px`);
 }
 assert.ok(publicQueries>0,'Public RPC fallback was used');assert.deepEqual(errors,[]);console.log('No browser errors. Mocks are automated test fixtures only.');
}finally{await browser.close();server.close();}
