import {createPublicClient,http,custom,parseAbi,formatUnits} from 'viem';
import {readOwnedFriends} from '../vendor/friendsdk/owned-friends.ts';
import {readGenerationEligibility} from '../vendor/friendsdk/identity.ts';
import {createGenerationSpriteReader,GENERATION_SPRITE_MANIFEST,spriteFrame,decodeGenerationSprites} from '../vendor/friendsdk/generation-sprites.ts';
import {ITEMS,freshProgress,validateProgress,buy,record,reward} from './progress.js';
import {createRun,stepRun,W,H,WALLS} from './engine.js';
import './theme.css';
import {installFriendOSAPI} from './api.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const manifest=GENERATION_SPRITE_MANIFEST;
const publicClient=createPublicClient({transport:http(manifest.rpcUrl,{timeout:12000,retryCount:1}),cacheTime:0});
let demo=false;
let client=publicClient,provider=null,account=null,chain=null,friends=[],friend=null,sprites=null,progress=null,active='home',busy=false,epoch=0,run=null,raf=0,previous=0,keys=new Set(),destination=null,touch={x:0,y:0},memory=null,memoryTimer=null,muted=true,audio=null,status='Connect your wallet to meet your Friend.',liveBalance=null;
const discovered=new Map();
const notifyAPI=installFriendOSAPI(()=>friend&&progress?{demo,identity:{tokenId:friend.id.toString(),generation:friend.generation,family:sprites?.familyName,wallet:friend.walletAddress,verifiedBlock:friend.verifiedBlock.toString()},progress,mode:demo?'demo':'simulated',storage:'browser-local'}:null,navigate);
window.addEventListener('eip6963:announceProvider',e=>{if(e.detail?.provider)discovered.set(e.detail.info.uuid,e.detail);renderGate();});window.dispatchEvent(new Event('eip6963:requestProvider'));
const storageKey=()=>demo?'friendos:demo:v1':`friendos:v1:4663:${friend.walletAddress.toLowerCase()}:${friend.id}`;
function save(){notifyAPI();try{localStorage.setItem(storageKey(),JSON.stringify(progress));$('#save-state').textContent='Saved on this browser';}catch{$('#save-state').textContent='Browser save unavailable · use Export';}}
function load(){try{const raw=localStorage.getItem(storageKey());return raw?validateProgress(JSON.parse(raw)):freshProgress();}catch{return freshProgress();}}
function toast(s){$('#feedback').textContent=s;$('#feedback').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#feedback').classList.remove('visible'),5000);}
function invalidate(message){epoch++;$('#confirm').close();$('#reset').close();friend=null;sprites=null;progress=null;liveBalance=null;stopGames();active='home';status=message;notifyAPI();render();}
function stopGames(){cancelAnimationFrame(raf);raf=0;keys.clear();touch={x:0,y:0};destination=null;clearTimeout(memoryTimer);if(run?.phase==='running')run.phase='paused';}
function renderGate(){if(friend)return;const choices=[...discovered.values()];$('#gate-actions').innerHTML=choices.length?choices.map((w,i)=>`<button class="primary" data-wallet="${i}">Connect ${esc(w.info.name)}</button>`).join(''):'<button class="primary" id="connect">Connect wallet</button>';if(account&&chain!==4663)$('#gate-actions').innerHTML+='<button class="secondary" id="switch">Switch to Robinhood</button>';if(account&&chain===4663)$('#gate-actions').innerHTML+='<button class="secondary" id="retry">Retry discovery</button>';$('#gate-actions').innerHTML+='<button class="secondary" id="demo">Explore demo without a wallet</button>';$('#gate-status').textContent=status;$('#friend-list').innerHTML=friends.map((f,i)=>`<button class="friend-choice" data-select="${i}"><span>Friend #${f.id}</span><small>Generation ${f.generation} · Select</small></button>`).join('');$('#gate').hidden=false;$('#workspace').hidden=true;$('#connection').textContent=busy?'Working…':account?`${account.slice(0,6)}…${account.slice(-4)}`:'Not connected';}
async function connect(index){if(busy)return;provider=index!==undefined?[...discovered.values()][index]?.provider:window.ethereum||[...discovered.values()][0]?.provider;if(!provider?.request){status='No browser wallet found. Open this page in your wallet’s browser or enable its extension.';renderGate();return;}busy=true;status='Waiting for your wallet…';renderGate();try{const accounts=await provider.request({method:'eth_requestAccounts'});account=accounts[0]||null;chain=Number(BigInt(await provider.request({method:'eth_chainId'})));provider.removeListener?.('accountsChanged',changedAccounts);provider.removeListener?.('chainChanged',changedChain);provider.on?.('accountsChanged',changedAccounts);provider.on?.('chainChanged',changedChain);client=createPublicClient({transport:custom(provider),cacheTime:0});if(!account)throw new Error('No account selected');if(chain!==4663){status='Switch to Robinhood mainnet (4663) to find your Friends.';}else await discover();}catch(e){status=e.code===4001?'Connection declined. You can try again.':e.message||'Connection failed';}finally{busy=false;render();}}
function changedAccounts(a){if(demo)return;account=a[0]||null;friends=[];invalidate('Account changed. Verify your Friend again.');if(account&&chain===4663)void refresh();}
function changedChain(c){if(demo)return;chain=Number(BigInt(c));friends=[];invalidate('Network changed. Verify your Friend again.');if(account&&chain===4663)void refresh();}
async function discover(){const version=++epoch;friends=[];status='Reading your account’s Friend transfer history…';renderGate();const result=await readOwnedFriends(client,account);if(version!==epoch)return;friends=[...result.friends];status=friends.length?'Choose your Friend below.':result.hiddenCount?'Your Generations NFTs are generation 0. A hardwired generation 1+ Friend is required.':'No Rare Friends Generations NFTs found in this account.';}
async function refresh(){if(busy)return;busy=true;try{await discover();}catch(e){status=e.message;}finally{busy=false;renderGate();}}
async function switchNetwork(){try{await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x1237'}]});}catch(e){if(e.code===4902){await provider.request({method:'wallet_addEthereumChain',params:[{chainId:'0x1237',chainName:'Robinhood',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:[manifest.rpcUrl],blockExplorerUrls:['https://robinhoodchain.blockscout.com']}]});}else{status=e.message;renderGate();}}}
async function selectFriend(index){if(busy||!friends[index])return;busy=true;const selected=friends[index],version=++epoch;status=`Verifying Friend #${selected.id} at a fresh block…`;renderGate();try{const eligible=await readGenerationEligibility(client,selected.id,account);if(!eligible.eligible)throw new Error('Ownership or hardwiring could not be verified.');const art=await createGenerationSpriteReader(client).read(selected.id);if(version!==epoch)return;friend={...selected,generation:eligible.generation,verifiedBlock:eligible.blockNumber};sprites=art;progress=load();record(progress,`Verified Friend #${friend.id} · generation ${friend.generation}.`);save();active='home';void refreshBalance();}catch(e){status=e.message||'Could not load your Friend.';}finally{busy=false;render();}}
async function verify(){if(demo&&friend?.kind==='demo')return true;if(!friend)throw new Error('Select your Friend first');const version=epoch;const selected=friend;const result=await readGenerationEligibility(client,selected.id,account);if(version!==epoch||!result.eligible) {invalidate('Your Friend’s ownership or network changed. Reconnect to continue.');throw new Error('Friend verification changed');}return true;}
async function refreshBalance(){if(demo)return;if(!friend)return;const selected=friend;try{const value=await client.readContract({address:'0x0779369854d3EcdEA927206718FFD7730C67B71f',abi:parseAbi(['function balanceOf(address) view returns (uint256)']),functionName:'balanceOf',args:[selected.walletAddress]});if(friend===selected){liveBalance=formatUnits(value,18);if(active==='wallet')renderPanel();}}catch{if(friend===selected)liveBalance='Unavailable · retry';}}
function character(canvas,size=5,facing='down',walking=false,frame=0){if(!sprites)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const rows=spriteFrame(sprites,facing,walking,frame).frame.rows;ctx.fillStyle='#f2f8de';rows.forEach((r,y)=>[...r].forEach((b,x)=>{if(b==='#')ctx.fillRect(x*size,y*size,size,size);}));}
function render(){if(!friend){renderGate();return;}$('#gate').hidden=true;$('#workspace').hidden=false;$('#connection').textContent=demo?'DEMO · NO WALLET':`${account.slice(0,6)}…${account.slice(-4)}`;$('#friend-name').textContent=demo?'Demo Friend':`Friend #${friend.id}`;$('#friend-meta').textContent=demo?'Sample avatar · not an NFT':`${sprites.familyName} · Gen ${friend.generation}`;$('#change-friend').textContent=demo?'Use my real Friend':'Change Friend';$('#mode-note').textContent=demo?'Interactive demo · sample identity · all credits, items and balances simulated':'Simulated economy / Real NFT identity';$('#credits').textContent=progress.credits;$('#xp').textContent=`${progress.xp} XP`;$('#level').textContent=`Expedition ${progress.level}`;$('#selected-name').textContent=demo?'INTERACTIVE DEMO':`Friend #${friend.id}`;character($('#portrait'),6);document.querySelectorAll('[data-app]').forEach(el=>el.classList.toggle('selected',el.dataset.app===active));renderPanel();}
const itemTile=(id)=>`<article class="item-card"><span class="item-icon">${ITEMS[id].icon}</span><h3>${ITEMS[id].name}</h3><p>${ITEMS[id].effect}</p><small>Simulated collectible</small>${progress.items.includes(id)?`<button class="secondary" data-equip="${id}">${progress.equipped===id?'Unequip':'Equip'}</button>`:ITEMS[id].cost?`<button class="primary" data-buy="${id}" ${progress.credits<ITEMS[id].cost?'disabled':''}>Craft · ${ITEMS[id].cost} preview RF</button>`:'<span class="locked">Complete an expedition to unlock</span>'}</article>`;
function renderPanel(){const panel=$('#panel');$('#app-heading').textContent={home:'Your home',run:'Relic Run',memory:'Memory Grove',inventory:'Inventory',shop:'Workshop',wallet:'Friend wallet',activity:'Activity',settings:'Settings'}[active];
if(active==='home')panel.innerHTML=`<div class="home-banner"><div><span class="eyebrow">YOUR FRIEND HAS PLACES TO BE</span><h2>A little adventure.<br>A growing collection.</h2><p>Gather six relics, dodge the wisps, and make it home before the portal closes.</p><button class="primary" data-app="run">Play Relic Run</button></div><div class="home-stat"><strong>${progress.wins}</strong><span>expeditions completed</span></div></div><div class="game-cards"><button class="game-card run-card" data-app="run"><span class="game-glyph">✦</span><div><small>EXPLORE · COLLECT · ESCAPE</small><h3>Relic Run</h3><p>90 seconds. Six relics. One way home.</p></div><span class="play-label">Play</span></button><button class="game-card memory-card" data-app="memory"><span class="game-glyph">◈</span><div><small>STUDY · MATCH · REMEMBER</small><h3>Memory Grove</h3><p>Find six pairs before the timer runs out.</p></div><span class="play-label">Play</span></button></div><div class="home-bottom"><div><h3>Take your finds with you.</h3><p>Craft shoes, a shield or a lantern. Equip one item; its effect applies in the compatible game.</p><button class="secondary" data-app="inventory">Open inventory</button></div><div class="sim-note">All credits, items and rewards are simulated. Your NFT identity and wallet address are real.</div></div>`;
if(active==='inventory')panel.innerHTML=`<p class="panel-note">Collection for ${demo?'Demo Friend':`Friend #${friend.id}`}. Saved on this browser; these are offchain preview items.</p><div class="item-grid">${progress.items.length?progress.items.map(itemTile).join(''):'<div class="empty"><h3>Your shelf is waiting.</h3><p>Win Relic Run to earn an Explorer Badge, or craft equipment in Workshop.</p><button class="primary" data-app="run">Start exploring</button></div>'}</div>`;
if(active==='shop')panel.innerHTML=`<p class="panel-note">Craft equipment using simulated RF. No token approvals or wallet transactions. One item can be equipped at a time.</p><div class="item-grid">${Object.keys(ITEMS).filter(k=>ITEMS[k].cost).map(itemTile).join('')}</div>`;
if(active==='wallet'&&demo)panel.innerHTML=`<div class="wallet-grid"><article class="data-card"><small>EXAMPLE FRIEND WALLET · SIMULATED BALANCE</small><h2>25 <span>RF</span></h2><p>This is sample data for the walkthrough, not a blockchain balance.</p></article><article class="data-card preview-card"><small>SPENDABLE DEMO CREDITS</small><h2>${progress.credits} <span>RF</span></h2><p>Use these in Workshop. Win either game to earn more.</p></article></div><dl class="profile-data"><dt>Identity</dt><dd>Demo Friend · sample avatar · no NFT</dd><dt>Wallet</dt><dd>No wallet connected</dd><dt>Progress</dt><dd>Saved separately in this browser’s demo profile</dd></dl><p class="panel-note">Connect your own Friend using “Use my real Friend” to see actual ownership, artwork and balances.</p>`;
if(active==='wallet'&&!demo)panel.innerHTML=`<div class="wallet-grid"><article class="data-card"><small>ACTUAL NFT-WALLET RF BALANCE · READ ONLY</small><h2>${liveBalance===null?'Reading…':esc(liveBalance)} <span>RF</span></h2><button class="secondary" id="balance-retry">Refresh balance</button></article><article class="data-card preview-card"><small>SIMULATED WORKSPACE CREDITS</small><h2>${progress.credits} <span>RF</span></h2><p>These credits have no cash value and cannot be withdrawn.</p></article></div><dl class="profile-data"><dt>Canonical NFT wallet</dt><dd>${friend.walletAddress}</dd><dt>Owner account</dt><dd>${account}</dd><dt>Collection</dt><dd>${manifest.generations}</dd><dt>Identity</dt><dd>Friend #${friend.id} · generation ${friend.generation} · ${sprites.familyName}</dd><dt>Verified at block</dt><dd>${friend.verifiedBlock}</dd><dt>Network</dt><dd>Robinhood mainnet · 4663</dd></dl><a class="source-link" href="https://robinhoodchain.blockscout.com/address/${friend.walletAddress}" target="_blank" rel="noopener noreferrer">View NFT wallet on explorer ↗</a>`;
if(active==='activity')panel.innerHTML=`<p class="panel-note">Local game history for this Friend. These are not blockchain transactions.</p><ul class="activity">${progress.history.map(h=>`<li><time>${new Date(h.at).toLocaleString()}</time><span>${esc(h.text)}</span></li>`).join('')}</ul>`;
if(active==='settings')panel.innerHTML=`<div class="settings"><h3>Your progress stays with this browser.</h3><p>It is saved under the selected NFT wallet and token ID. Export a backup to move it to another device. Saves are editable local preview data, not verified onchain achievements.</p><button class="secondary" id="export">Export progress</button><label class="secondary file-label">Import progress<input type="file" id="import" accept="application/json,.json"></label><button class="secondary" id="sound">${muted?'Enable sound':'Mute sound'}</button><button class="danger" id="reset-progress">Reset this Friend’s progress</button><p>No private keys, signatures, token approvals or transactions are requested by this app. Demo saves are separate from real Friend saves.</p></div>`;
if(active==='run'){run=createRun(progress.level,progress.equipped);panel.innerHTML='<div class="run-hud"><span id="run-hearts">♥ ♥ ♥</span><strong id="run-count">0 / 6 relics</strong><span id="run-time">90s</span><button class="secondary" id="pause-run">Pause</button></div><div class="canvas-wrap"><canvas id="game" width="960" height="560" tabindex="0" aria-label="Relic Run garden. Move with arrow keys, WASD, touch controls, or tap a destination."></canvas><div class="game-overlay" id="run-overlay"><span class="eyebrow">EXPEDITION '+progress.level+'</span><h2>Find your way home.</h2><p>Collect all six relics. Avoid the moving wisps.<br>Reach the bottom-right portal within 90 seconds.</p><small>Arrows / WASD · tap to move · 3 hearts<br>Win: +8 simulated RF, +30 XP</small><button class="primary" id="start-run">Begin expedition</button></div></div><div class="controls"><div class="dpad"><button data-move="up" aria-label="Move up">↑</button><button data-move="left" aria-label="Move left">←</button><button data-move="down" aria-label="Move down">↓</button><button data-move="right" aria-label="Move right">→</button></div><p>Relics: ✦ · Wisps: ◉ · Portal: ◎<br>'+ (progress.equipped?`Equipped: ${ITEMS[progress.equipped].name}`:'No equipment · visit Workshop for upgrades')+'</p></div>';bindCanvas();drawRun();}
if(active==='memory'){memory=null;panel.innerHTML=`<div class="memory-header"><div><h2>Memory Grove</h2><p>Study the symbols, then find six matching pairs.</p></div><span id="memory-time">60 seconds</span></div><div class="memory-board" id="memory-board"></div><div class="memory-footer"><p id="memory-status">Win: +5 simulated RF, +20 XP. Your Lantern extends study time.</p><button class="primary" id="start-memory">Start a round</button></div>`;$('#memory-board').innerHTML=Array.from({length:12},()=>'<div class="memory-placeholder">?</div>').join('');}
}
async function navigate(app){if(!friend)return;stopGames();active=app;render();}
function drawSprite(ctx,x,y,scale,facing,walking){if(!sprites)return;const rows=spriteFrame(sprites,facing,walking,Math.floor((run?.age||0)*8)%8).frame.rows;ctx.fillStyle='#eaffb3';rows.forEach((r,yy)=>[...r].forEach((b,xx)=>{if(b==='#')ctx.fillRect(Math.round(x-8*scale+xx*scale),Math.round(y-12*scale+yy*scale),scale,scale);}));}
function drawRun(){const canvas=$('#game');if(!canvas||!run)return;const ctx=canvas.getContext('2d');ctx.fillStyle='#142b25';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#254138';ctx.lineWidth=1;for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}ctx.strokeStyle='#406c52';ctx.lineWidth=7;ctx.strokeRect(12,12,W-24,H-24);WALLS.forEach(r=>{ctx.fillStyle='#314d3b';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle='#48744c';ctx.fillRect(r.x,r.y,r.w,8);ctx.strokeStyle='#688b52';ctx.lineWidth=2;ctx.strokeRect(r.x,r.y,r.w,r.h);});run.gems.forEach(g=>{if(g.found)return;ctx.fillStyle='#d9f982';ctx.font='38px sans-serif';ctx.textAlign='center';ctx.fillText('✦',g.x,g.y+12);});run.enemies.forEach(e=>{ctx.fillStyle='#f49e8b';ctx.beginPath();ctx.arc(e.x,e.y,14,0,Math.PI*2);ctx.fill();ctx.fillStyle='#42302a';ctx.beginPath();ctx.arc(e.x,e.y,5,0,Math.PI*2);ctx.fill();});ctx.strokeStyle=run.collected===6?'#d5ff87':'#537261';ctx.lineWidth=5;ctx.beginPath();ctx.arc(run.portal.x,run.portal.y,26,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#c8dbb4';ctx.font='14px sans-serif';ctx.fillText(run.collected===6?'HOME':'LOCKED',run.portal.x,run.portal.y+46);if(run.hitCooldown===0||Math.floor(run.age*12)%2===0)drawSprite(ctx,run.player.x,run.player.y,3,keys.has('ArrowLeft')||keys.has('a')?'left':keys.has('ArrowRight')||keys.has('d')?'right':'down',run.phase==='running');$('#run-count').textContent=`${run.collected} / 6 relics`;$('#run-time').textContent=`${Math.ceil(run.time)}s`;$('#run-hearts').textContent='♥ '.repeat(Math.max(0,run.hearts));}
function bindCanvas(){const c=$('#game');c.addEventListener('pointerdown',e=>{if(run?.phase!=='running')return;const r=c.getBoundingClientRect();destination={x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};c.focus();});}
async function startRun(){if(busy||!friend)return;busy=true;try{await verify();run.phase='running';$('#run-overlay').hidden=true;$('#game').focus();previous=performance.now();raf=requestAnimationFrame(tick);}catch(e){toast(e.message);}finally{busy=false;}}
function tick(now){if(active!=='run'||!run||run.phase!=='running')return;const dt=(now-previous)/1000;previous=now;let input={x:touch.x+(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0),y:touch.y+(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0)};if(destination&&!input.x&&!input.y){const dx=destination.x-run.player.x,dy=destination.y-run.player.y;if(Math.hypot(dx,dy)>8)input={x:dx,y:dy};else destination=null;}else if(input.x||input.y)destination=null;const count=run.collected,hp=run.hearts;stepRun(run,dt,input);if(count!==run.collected)beep(700);if(hp!==run.hearts)beep(130);drawRun();if(run.phase==='won'||run.phase==='lost'){finishRun();return;}raf=requestAnimationFrame(tick);}
function finishRun(){const won=run.phase==='won';if(won){reward(progress,'run');save();$('#credits').textContent=progress.credits;$('#xp').textContent=`${progress.xp} XP`;$('#level').textContent=`Expedition ${progress.level}`;}else{record(progress,'Relic Run ended. No preview RF lost.');save();}$('#run-overlay').hidden=false;$('#run-overlay').innerHTML=`<span class="eyebrow">${won?'EXPEDITION COMPLETE':'TRY ANOTHER PATH'}</span><h2>${won?'Your Friend made it home.':'The garden got you.'}</h2><p>${won?'+8 simulated RF · +30 XP<br>Explorer Badge added to your inventory.':run.time<=0?'Time ran out.':'You ran out of hearts.'}</p><button class="primary" data-app="run">${won?'Next expedition':'Try again'}</button><button class="secondary" data-app="inventory">Open inventory</button>`;beep(won?900:200);}
function pauseRun(){if(!run)return;if(run.phase==='running'){run.phase='paused';cancelAnimationFrame(raf);keys.clear();touch={x:0,y:0};$('#run-overlay').hidden=false;$('#run-overlay').innerHTML='<h2>Take a breath.</h2><p>The garden is paused.</p><button class="primary" id="resume-run">Resume expedition</button>';} }
async function resumeRun(){try{await verify();run.phase='running';$('#run-overlay').hidden=true;previous=performance.now();raf=requestAnimationFrame(tick);}catch(e){toast(e.message);}}
function shuffled(){const cards=['✦','◈','☾','✧','○','⌘'].flatMap(x=>[x,x]);for(let i=cards.length-1;i>0;i--){const n=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[cards[i],cards[n]]=[cards[n],cards[i]];}return cards;}
async function startMemory(){if(busy)return;busy=true;try{await verify();memory={cards:shuffled(),matched:[],open:[],studying:true,locked:false,remaining:60,started:0,done:false};const round=memory;$('#start-memory').disabled=true;$('#memory-status').textContent='Study the symbols. They’ll turn over shortly.';renderMemory();memoryTimer=setTimeout(()=>{if(memory!==round||active!=='memory')return;memory.studying=false;memory.started=Date.now();$('#memory-status').textContent='Find all six pairs.';renderMemory();memoryCountdown();},progress.equipped==='lantern'?5000:3000);}catch(e){toast(e.message);}finally{busy=false;}}
function renderMemory(){$('#memory-board').innerHTML=memory.cards.map((c,i)=>`<button class="memory-tile ${memory.matched.includes(i)?'matched':''}" data-card="${i}" aria-label="${memory.studying||memory.matched.includes(i)||memory.open.includes(i)?esc(c):'Hidden card '+(i+1)}" ${memory.studying||memory.matched.includes(i)||memory.done?'disabled':''}>${memory.studying||memory.matched.includes(i)||memory.open.includes(i)?c:'?'}</button>`).join('');}
function memoryCountdown(){if(active!=='memory'||!memory||memory.done)return;memory.remaining=Math.max(0,60-Math.floor((Date.now()-memory.started)/1000));$('#memory-time').textContent=`${memory.remaining}s`;if(!memory.remaining){memory.done=true;$('#memory-status').textContent='Time ran out. No credits lost. Try a new round.';$('#start-memory').disabled=false;$('#start-memory').textContent='Play again';renderMemory();return;}memoryTimer=setTimeout(memoryCountdown,250);}
function flip(i){if(!memory||memory.studying||memory.locked||memory.done||memory.open.includes(i)||memory.matched.includes(i))return;memory.open.push(i);renderMemory();if(memory.open.length===2){memory.locked=true;const round=memory;const [a,b]=memory.open;const matched=memory.cards[a]===memory.cards[b];setTimeout(()=>{if(active!=='memory'||memory!==round)return;if(matched){memory.matched.push(a,b);beep(650);}memory.open=[];memory.locked=false;if(memory.matched.length===12){memory.done=true;reward(progress,'memory');save();$('#credits').textContent=progress.credits;$('#xp').textContent=`${progress.xp} XP`;$('#memory-status').textContent='Grove restored! +5 simulated RF, +20 XP.';$('#start-memory').disabled=false;$('#start-memory').textContent='Play again';}renderMemory();},matched?300:850);}}
function beep(freq){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();void audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=freq;g.gain.setValueAtTime(.03,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);o.start();o.stop(audio.currentTime+.1);}catch{}}
document.addEventListener('click',async e=>{const t=e.target.closest('button,a,label');if(!t)return;if(t.dataset.app){void navigate(t.dataset.app);return;}if(t.dataset.wallet!==undefined){void connect(Number(t.dataset.wallet));return;}if(t.dataset.select!==undefined){void selectFriend(Number(t.dataset.select));return;}if(t.dataset.card!==undefined){flip(Number(t.dataset.card));return;}if(t.dataset.equip){progress.equipped=progress.equipped===t.dataset.equip?null:t.dataset.equip;record(progress,progress.equipped?`Equipped ${ITEMS[progress.equipped].name}.`:'Equipment removed.');save();renderPanel();return;}if(t.dataset.buy){$('#confirm-text').textContent=`Craft ${ITEMS[t.dataset.buy].name} for ${ITEMS[t.dataset.buy].cost} simulated RF? No real funds are involved.`;$('#confirm-action').dataset.item=t.dataset.buy;$('#confirm').showModal();return;}switch(t.id){case'connect':void connect();break;case'switch':void switchNetwork();break;case'retry':void refresh();break;case'change-friend':demo=false;friends=[];account=null;chain=null;invalidate('Connect your wallet to verify your actual Friend, or return to the demo.');break;case'demo':startDemo();break;case'start-run':void startRun();break;case'pause-run':pauseRun();break;case'resume-run':void resumeRun();break;case'start-memory':void startMemory();break;case'balance-retry':void refreshBalance();break;case'sound':muted=!muted;renderPanel();break;case'confirm-cancel':$('#confirm').close();break;case'confirm-action':if(buy(progress,t.dataset.item)){save();toast('Equipment crafted with simulated RF.');}else toast('Unable to craft: already owned or insufficient credits.');$('#confirm').close();render();break;case'export':{const data={friendId:friend.id.toString(),wallet:friend.walletAddress,progress};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`friend-os-${friend.id}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}case'reset-progress':$('#reset').showModal();break;case'reset-cancel':$('#reset').close();break;case'reset-confirm':progress=freshProgress();save();$('#reset').close();render();break;}});
document.addEventListener('change',async e=>{if(e.target.id==='import'&&e.target.files[0]){try{const file=e.target.files[0];if(file.size>100000)throw new Error('Backup too large');const data=JSON.parse(await file.text());if(data.friendId!==friend.id.toString()||data.wallet?.toLowerCase()!==friend.walletAddress.toLowerCase())throw new Error('This backup belongs to another Friend');progress=validateProgress(data.progress);save();render();toast('Progress restored.');}catch(err){toast(err.message);}}});
document.addEventListener('keydown',e=>{if(active==='run'&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)&&!$('#confirm').open){e.preventDefault();keys.add(e.key);}if(e.key==='Escape'&&active==='run')pauseRun();});document.addEventListener('keyup',e=>keys.delete(e.key));
document.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-move]');if(b){e.preventDefault();b.setPointerCapture?.(e.pointerId);touch={x:b.dataset.move==='left'?-1:b.dataset.move==='right'?1:0,y:b.dataset.move==='up'?-1:b.dataset.move==='down'?1:0};}});document.addEventListener('pointerup',()=>touch={x:0,y:0});document.addEventListener('pointercancel',()=>touch={x:0,y:0});window.addEventListener('blur',()=>{keys.clear();pauseRun();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();pauseRun();}});

function startDemo(){
 epoch++;stopGames();busy=false;demo=true;account=null;chain=null;friends=[];
 friend={id:0n,kind:'demo',label:'Demo Friend',walletAddress:'demo',generation:0,verifiedBlock:0n};
 let bitmap=0n;for(let y=0;y<16;y++)for(let x=0;x<16;x++){if(Math.abs(x-7.5)+Math.abs(y-7.5)<5.8&&!(x>=6&&x<=9&&y>=6&&y<=9))bitmap|=1n<<BigInt(y*16+x);}
 sprites={...decodeGenerationSprites(1n,0,0,Array(64).fill(bitmap)),familyName:'Demo avatar'};
 progress=load();active='home';render();save();
}
startDemo();
